### ISSUE TITLE
Sprint-0 Set up Next.js 

### ISSUE THREAD

**Issue by osman-sultan** [mishasinitcyn/RepoCleanup-frontend#1]
## Location
Entire root directory

## Expectation
Setup next.js for full stack development of web app

## Tasks
- [x] Initialize next.js project
- [x] Add shadcn/ui dependencies 
- [x] Update readme for setup instructions
