### ISSUE TITLE
Sprint-2 Frontend Themeing + Hero Section

### ISSUE THREAD

**Issue by osman-sultan** [mishasinitcyn/RepoCleanup-frontend#5]
## Location
`page.tsx` `components folder`

## Expectation
Dark mode + light mode, gradient bg, appealing hero section

## Tasks
- [x] Add dark mode/light mode toggle
- [x] Add gradient bg
- [x] Beutify hero section
